### ISSUE TITLE
关于ycsb的数据格式

### ISSUE THREAD

**Issue by penhison** [ZhangJiaQiao/2019-DBMS-Project#10]
INSERT 6284781860667377211
ycsb测试的条目的键值都为8字节，是指将6284781860667377211视为一个uint64_t，键和值都为这个8字节的值，还是截取前8个数字如62847818作为键和值的值？

**Comment by ZhangJiaQiao** [comment]
截取前8字节，不是8个数字

**Comment by penhison** [comment]
我现在的做法是将操作后面的数字如6284781860667377211视为一个10进制的类型为uint64_t的数字，这样后面这一部分就是刚好只有8个字节，同时将这个值作为键和值的值插入到数据库，这样子是否正确？

**Comment by ZhangJiaQiao** [comment]
最好还是截取前8字节，但是这个数本来都是随机的，所以理论上截取哪里都没事，反正够8字节就行。但是还是截取前8字节比较好
