### ISSUE TITLE
 maxFileId

### ISSUE THREAD

**Issue by IYreality** [ZhangJiaQiao/2019-DBMS-Project#12]
那个maxfield在readme里面说是记录分配文件的最大标号，那么是分配一个文件就加一还是一开始建立树的时候就确定了多大(但是这样数据大量存储肯定就有限制，所以感觉是第一种)，但是在注释里面又说它是当前没有被使用的fileID，所以是不是又得理解成剩余还有多少空间可分配的意思？

**Comment by ZhangJiaQiao** [comment]
maxfileid是单前还没分配的标号，比如4的话就说明1-3都被分配了，4是还没被分配的
