### ISSUE TITLE
newLeafGroup

### ISSUE THREAD

**Issue by 17343149** [ZhangJiaQiao/2019-DBMS-Project#13]
如果一个leafGroup代表一个文件的话, 那么p_allocator.cpp中的newLeafGroup()分配一个新的leafGroup, 也就是说新文件该怎么命名呢?

**Comment by IYreality** [comment]
readme里面说了用依次增加的整数命名，从1开始

**Comment by ZhangJiaQiao** [comment]
上面同学说的对，请仔细看完说明文档
