### ISSUE TITLE
LeafGroup与freeList

### ISSUE THREAD

**Issue by 17343149** [ZhangJiaQiao/2019-DBMS-Project#16]
LeafGroup结构：| usedNum(8 bytes) | bitmap(n bytes) | Leaf1 | ... | leafN |
    catelog：| maxFileId(8 bytes) | freeNum(8 bytes) | treeStartLeaf(PPointer) |
    freeList：| (fId, offset)1, ..., (fId)N |
三个文件都是定长的话, leafGroup前面两个是8字节+16字节, 后面的从Leaf1到LeafN的大小该怎么确定呢? freeList的文件大小该怎么确定?(有点头秃)
从文件映射到虚拟地址时flag用 PMEM_FILE_CREATE 可以映射已经存在的文件吗?

**Comment by ZhangJiaQiao** [comment]
叶子的大小可以确定啊，知道度了就知道有多少元素，然后键和值都是8字节，一个叶子的大小就可以确定了。freelist是变化的，但是里面每个元素都是16字节的。这个flag可以
