### ISSUE TITLE
lycsb测试leveldb的编译问题

### ISSUE THREAD

**Issue by core37** [ZhangJiaQiao/2019-DBMS-Project#18]
/usr/bin/ld: /tmp/ccB0tH2v.o: in function `main':
lycsb.cpp:(.text+0x26): undefined reference to `leveldb::Options::Options()'
/usr/bin/ld: lycsb.cpp:(.text+0x8f): undefined reference to `leveldb::DB::Open(leveldb::Options const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, leveldb::DB**)'
collect2: error: ld returned 1 exit status

求问是否需要增加特殊的编译指令？

**Comment by ZhangJiaQiao** [comment]
levelDB的链接没成功吧，先安装levelDB先，作为系统库或者一个外部库链接

**Comment by core37** [comment]
已经安装了，能通过引用查询到levelDB源代码

**Comment by ZhangJiaQiao** [comment]
安装了重启下系统看下




------------------ 原始邮件 ------------------
发件人: "core37"<notifications@github.com>; 
发送时间: 2019年5月4日(星期六) 晚上10:29
收件人: "ZhangJiaQiao/2019-DBMS-Project"<2019-DBMS-Project@noreply.github.com>; 
抄送: "Killin'machine"<1254860908@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [ZhangJiaQiao/2019-DBMS-Project] lycsb测试leveldb的编译问题 (#18)




已经安装了，能通过引用查询到levelDB源代码
