### ISSUE TITLE
课程设计里的FPTree是Apriori的优化算法吗？

### ISSUE THREAD

**Issue by IYreality** [ZhangJiaQiao/2019-DBMS-Project#2]
查资料时发现有个Apriori算法和PFtree有关，但是看论文这个好像又和Apriori没什么关系，所以不知道和Apriori有关的那个tree是不是就是我们要用到的这个FPTree呢？

**Comment by ZhangJiaQiao** [comment]
先不用管其他的论文，先做好这个。FPTree还有一个同名的树叫Frequent Pattern tree，和这次课程设计无关。所以你们不要想通过百度找参考，找到的都不是这次课程设计用的
