### ISSUE TITLE
fptree_test.cpp 错误

### ISSUE THREAD

**Issue by ctlchild** [ZhangJiaQiao/2019-DBMS-Project#20]
https://github.com/ZhangJiaQiao/2019-DBMS-Project/blob/855ce4155e5eeddedc166701280ca412b2abe50c/Programming-FPTree/test/fptree_test.cpp#L79-L82
这里只修改 key 为 1 3 5 7 等奇数 key 的 value 为 key×200，偶数 key 2 4 6 等仍然为 key×100
但是：
https://github.com/ZhangJiaQiao/2019-DBMS-Project/blob/855ce4155e5eeddedc166701280ca412b2abe50c/Programming-FPTree/test/fptree_test.cpp#L86-L88
这里的检查却检查所有 key 的 value 是不是 key×200

因此 fp_tree_test.cpp 这里有误

**Comment by ZhangJiaQiao** [comment]
的确有问题，好像删多了东西，待会更新

**Comment by ZhangJiaQiao** [comment]
已修正
