### ISSUE TITLE
degree定义

### ISSUE THREAD

**Issue by Eayne** [ZhangJiaQiao/2019-DBMS-Project#22]
我的理解的话，是leafnode的最大degree是utility.h定义的LEAF_DEGREE，innernode的最大的degree也是定义好的INNER_DEGREE
如果是这样理解的话，那leafnode和innernode定义的成员变量degree是用来干嘛的，fptree的degree是什么作用。
如果不这样理解的话，那leafnode和innernode定义的degree就是最大degree。那要怎么获得degree，fptree类的degree是私有变量，又没有接口方法获得fptree的degree

**Comment by ZhangJiaQiao** [comment]
叶子的degree是要事先确定的，通过LEADF_DEGREE。但是中间节点的degree可以实时设置，通过FPTree这个类的构造的时候确定

**Comment by Eayne** [comment]
那定义的INNER_DEGREE有什么作用呢

**Comment by ZhangJiaQiao** [comment]
TA实验时用的最大的度

**Comment by Eayne** [comment]
OK，谢谢TA

**Comment by ZhangJiaQiao** [comment]
根据论文里的中间节点度的建议设置
