### ISSUE TITLE
关于叶分裂的处理问题

### ISSUE THREAD

**Issue by core37** [ZhangJiaQiao/2019-DBMS-Project#24]
1.根据伪代码貌似是寻找中间键，之后完全移动源页的数据，这个做法感觉有点怪，是否是正确的？
2.但是注释中的寻找中间键的过程中提示删除左侧的内容，此时按照伪代码流程，数据还未被复制，直接删除不是就会丢失数据吗？这个是不是注释有误，把split的任务安排在findSplitKey中了？

**Comment by ZhangJiaQiao** [comment]
是说叶子分裂的过程吗，叶子的split里应该要调用findSplitKey找寻中间的键值，然后小于这个键值的分给一个叶子，大于这个键值的元素分给另一个叶子，这个过程只需复制一下原来的叶子，然后对应设置他们的bitmap即可。
